{% set python_min = '3.11.0' %}
{% set name = "django-webhook" %}
{% set version = "0.0.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_webhook-{{ version }}.tar.gz
  sha256: bcf1e15b1341c5bfef886b715ab376aa5a8432ed06ea654703a8257c7b4f05c5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry >=0.12
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - django >=4.0,<6.0
    - django-model-utils >=4.0,<5.0
    - celery >=5.0,<6.0
    - requests >=2.0,<3.0

test:
  imports:
    - django_webhook
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/danihodovic/django-webhook/
  summary: Django webhooks triggered on model changes
  doc_url: https://django-webhook.readthedocs.io/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
